# Disease Outbreak Early Warning System

## Notebook 01: Data Collection and Integration

### Purpose

The objective of this notebook is to collect, inspect, and integrate dengue surveillance data for subsequent time series analysis and outbreak forecasting.

### Tasks

* Load dengue feature data
* Load dengue case count data
* Merge surveillance and environmental datasets
* Inspect data quality
* Assess missing values
* Prepare the dataset for exploratory analysis

### Expected Outcome

A unified dengue surveillance dataset containing epidemiological and environmental variables that can be used for outbreak detection and forecasting.

Import Libraries

In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries imported successfully.")

Libraries imported successfully.

## Loading the Dataset

The dengue forecasting dataset consists of environmental measurements and weekly dengue case counts.

The environmental variables include rainfall, humidity, temperature, and vegetation indices that may influence disease transmission dynamics.

In [4]:
features = pd.read_csv(
    "/content/dengue_labels_train.csv"
)

labels = pd.read_csv(
    "/content/dengue_labels_train.csv"
)

print("Features Shape:", features.shape)
print("Labels Shape:", labels.shape)

Features Shape: (1456, 4)
Labels Shape: (1456, 4)

## Inspecting the Data Structure

Before merging the datasets, it is important to understand the available variables and verify that the datasets contain the expected observations.

In [5]:
features.head()

  city  year  weekofyear  total_cases
0   sj  1990          18            4
1   sj  1990          19            5
2   sj  1990          20            4
3   sj  1990          21            3
4   sj  1990          22            6

In [6]:
labels.head()

  city  year  weekofyear  total_cases
0   sj  1990          18            4
1   sj  1990          19            5
2   sj  1990          20            4
3   sj  1990          21            3
4   sj  1990          22            6

## Dataset Integration

The environmental features and dengue case counts are merged using the common identifiers:

* City
* Year
* Epidemiological Week

This creates a single dataset for analysis.

In [7]:
dengue_df = pd.merge(
    features,
    labels,
    on=[
        "city",
        "year",
        "weekofyear"
    ]
)

dengue_df.head()

  city  year  weekofyear  total_cases_x  total_cases_y
0   sj  1990          18              4              4
1   sj  1990          19              5              5
2   sj  1990          20              4              4
3   sj  1990          21              3              3
4   sj  1990          22              6              6

In [8]:
print(
    "Merged Dataset Shape:",
    dengue_df.shape
)

Merged Dataset Shape: (1456, 5)

## Data Quality Assessment

Missing values are common in epidemiological and environmental surveillance systems.

Understanding the extent of missingness helps guide preprocessing decisions in later stages of the project.

In [9]:
missing_values = (
    dengue_df.isnull()
    .sum()
    .sort_values(
        ascending=False
    )
)

missing_values[
    missing_values > 0
]

Series([], dtype: int64)

In [10]:
dengue_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1456 entries, 0 to 1455
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   city           1456 non-null   object
 1   year           1456 non-null   int64
 2   weekofyear     1456 non-null   int64
 3   total_cases_x  1456 non-null   int64
 4   total_cases_y  1456 non-null   int64
dtypes: int64(4), object(1)
memory usage: 57.0+ KB

## Initial Observations

The integrated dataset combines disease incidence information with environmental factors that may influence dengue transmission.

The next stage of the project will focus on exploratory time series analysis to understand disease trends, seasonality, and geographic differences between cities.